# Generated by Django 2.0.7 on 2020-09-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rh', models.CharField(default='00000000', max_length=10)),
                ('nome', models.CharField(max_length=120)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('cor', models.CharField(max_length=10)),
            ],
        ),
    ]
