# Generated by Django 3.1.1 on 2020-11-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames_tecp', '0002_auto_20200905_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame_tecp',
            name='pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to='tecp/pdfs/'),
        ),
    ]
